name: be-ci

on:
  push:
    branches: [ "be/**" ]
    paths:
      - ".github/workflows/be.yml"
      - "back-end/**"
  pull_request:
    branches: [ "main" ]

jobs:
  be-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: back-end
    - run: npm run build
      working-directory: back-end
    - run: npm test --verbose
      working-directory: back-end
